CREATE TYPE role_enum AS ENUM ('ADMIN', 'CAREGIVER', 'GUARDIAN');

ALTER TABLE admin
ADD COLUMN role role_enum NOT NULL DEFAULT 'ADMIN';

ALTER TABLE caregiver
ADD COLUMN role role_enum NOT NULL DEFAULT 'CAREGIVER';

ALTER TABLE guardian
ADD COLUMN role role_enum NOT NULL DEFAULT 'GUARDIAN';