
CREATE TYPE report_status AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
    );

CREATE TYPE file_type AS ENUM (
    'IMAGE',
    'PDF',
    'VIDEO',
    'OTHER'
    );


CREATE TABLE caregiver_report (

report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
patient_caregiver_id BIGINT NOT NULL,
report_date_start DATE,
report_date_end DATE,
report_content TEXT,
observations TEXT,
status report_status NOT NULL DEFAULT 'PENDING',
created_at           TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_caregiver_report FOREIGN KEY (patient_caregiver_id)
    REFERENCES patient_caregiver(patient_caregiver_id)
);

CREATE TABLE caregiver_report_document
(
    doc_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id     BIGINT  NOT NULL,
    file_url      TEXT,
    file_type     VARCHAR(100),
    mime_type     VARCHAR(100),
    uploaded_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_caregiver_report_document FOREIGN KEY (report_id)
        REFERENCES caregiver_report(report_id)
);
